# Copyright (c) 2025 VH & Co BV. Licensed under the Business Source License 1.1. See LICENSE for details.

name: Release

on:
  push:
    tags:
      - '*.*.*'

permissions:
  contents: read
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build and push
        uses: michielvha/docker-release-action@main
        with:
          version: ${{ github.ref_name }}
          registry: ghcr.io
          username: vhco-pro
          password: ${{ secrets.GITHUB_TOKEN }}
          project: stackweaver-zitadel-init
          platforms: linux/amd64,linux/arm64
          context: .
